name: Deploy Backend to Lambda

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Run backend tests
        run: |
          cd backend
          echo "🧪 Running backend tests..."
          npm test
          echo "📊 Running test coverage..."
          npm run test:coverage

      - name: Create deployment zip
        run: |
          cd backend
          zip -r ../backend.zip . -x "*.git*" ".github/*" "terraform/*" "tests/*" "coverage/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to Lambda
        run: |
          aws lambda update-function-code \
            --function-name guest-parking-backend \
            --zip-file fileb://backend.zip

      - name: Wait for function update to complete
        run: |
          echo "Waiting for Lambda to finish updating..."
          aws lambda wait function-updated --function-name guest-parking-backend

      - name: Update Lambda Runtime to Node.js 22
        run: |
          aws lambda update-function-configuration \
            --function-name guest-parking-backend \
            --runtime nodejs22.x