name: Deploy Backend to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Zip backend and upload to S3
        run: |
          zip -r backend.zip . -x "*.git*" "node_modules/*"
          aws s3 cp backend.zip s3://$AWS_S3_BUCKET/deployments/latest/backend.zip --region $AWS_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_REGION=${{ secrets.AWS_REGION }}
            export AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}

            sudo yum install -y unzip nodejs npm aws-cli

            rm -rf backend.zip backend

            aws s3 cp s3://$AWS_S3_BUCKET/deployments/latest/backend.zip backend.zip --region $AWS_REGION

            unzip -o backend.zip -d backend
            cd backend
            npm install

            fuser -k 3000/tcp || true
            nohup node index.js > out.log 2>&1 &

