name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip source
        run: zip -r backend.zip . -x "*.git*"

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exact-timestamps
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "./"
          DEST_DIR: "deployments/latest"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo apt update
            sudo apt install unzip nodejs npm -y
            aws s3 cp s3://${{ secrets.S3_BUCKET }}/deployments/latest/backend.zip backend.zip
            unzip -o backend.zip -d backend
            cd backend
            npm install
            PORT=3000 nohup node index.js > out.log 2>&1 &
