name: Keep Supabase Awake

on:
  schedule:
    - cron: '0 0 */3 * *'   # Every 3 days at midnight UTC
  workflow_dispatch:        # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase awake via call to /availability
        run: curl -sSf https://aso4mwrw90.execute-api.us-east-1.amazonaws.com/api/bookings/availability?weekend=2025-07-18